### ISSUE TITLE
Python 2 lz4 issues

### ISSUE THREAD

**Issue by theboy181** [reswitched/loaders#18]
every time I try to install this loader I have issues.

Can you please halp me find a definitive way to install this for IDA 7.0

Fresh install on current Windows 10

**Comment by theboy181** [comment]
I just completed another FRESH install of Windows10 Pro.

I installed Python 2 with ``python-2.7.18.amd64``
Then from a command window ran ``pip install lz4``

When I try to load ``main`` with ida64 7.0 I get this error
![image](https://user-images.githubusercontent.com/9299743/121786180-104b9b00-cb73-11eb-88a5-42d6d142f141.png)

I have resolved this error on different installations in the past, but I am never clear on what I actually did to resolve it.

![image](https://user-images.githubusercontent.com/9299743/121786646-08412a80-cb76-11eb-9fa6-2c4d466590b5.png)

**Comment by Jenrikku** [comment]
You can't longer use lz4 with Python 2 as long as I know. You'll need to change to Python 3 with a newer version of IDA (7.5 or 7.4).

**Comment by theboy181** [comment]
Oddly I was able to setup and install in my laptop. not sure what the difference is here.

**Comment by SciresM** [comment]
This is untrue.

I setup python 2 lz4 in a new VM three days ago.

**Comment by SciresM** [comment]
2.2.1 isn't the right version of lz4 iirc, though.
