### ISSUE TITLE
Mario Golf

### ISSUE THREAD

**Issue by theboy181** [reswitched/loaders#20]
Cant seem to get a good decompile of this with the loader. xrefs are broken, and a limited amount of stuff is decompiled.

![image](https://user-images.githubusercontent.com/9299743/124392383-0caac000-dcaa-11eb-8b51-edccd9bf7b1f.png)

**Comment by theboy181** [comment]
See that its related to how it was compiled.

**Comment by SciresM** [comment]
The Loader works fine, Mario Golf does code obfuscation where most of its code is inside an NRO that the main executable decrypts + decompresses at runtime, for the record.

**Comment by theboy181** [comment]
Thanks - I hope that other games do not follow this, as the challenge of will make modding even more obscure than it already is.
