### ISSUE TITLE
Bizarre edge case in KIP1 decompression

### ISSUE THREAD

**Issue by hexkyz** [reswitched/loaders#3]
Certain kip1 files (e.g.: Loader) can have a discrepancy between the SectionHeader's CompressedSize and the compressed_data_len field in the footer.

Currently, a difference of one byte is detected in nxo64.py's line 30, but differences of up to 3 bytes have been detected.

**Comment by hthh** [comment]
Have you tried the fix with subtracting the difference from the `init_index` ( `init_index -= (len(compressed) - compressed_size)` ) ? I figured I wouldn't try to make the fix more general when I didn't have the files to test it.

**Comment by hexkyz** [comment]
Yes, I've tried that fix and it works fine in all scenarios I've came across.
