### ISSUE TITLE
Unity game mains are wrongly loaded

### ISSUE THREAD

**Issue by masagrator** [reswitched/loaders#8]
Something is wrong with loading Unity games executables.
I have tried Mages of Mystralia and Serial Cleaner. 
First one have mostly trash code. I have found only Steam part correctly disassembled.
Second one after couple of minutes is looped around Steam part.

So something with Steam-releated code is messing up loader.

**Comment by misson20000** [comment]
Can you show screenshots of what's going wrong?

**Comment by masagrator** [comment]
Never mind. Now it loaded without issue.
Weird...
